### ISSUE TITLE
export text/TSV etc

### ISSUE THREAD

**Issue by colindaven** [Protein-Sequence-Annotation/PSALM#1]
Hello,

thanks for an interesting package. How do you export other data types, eg text/TSV ? I'd like to inspect the predictions more.

Thanks
Colin

**Comment by ArpanSarkar** [comment]
Hi Colin,

I've just added a feature to save pickled versions of the entire family and clan prediction matrices for any sequence that you run "annotate" on. Example code/usage is below.

**Note: we should be releasing PSALM-1b soon, which will have faster annotation and be trained on all Pfam-35.0 domain families, which is not true for PSALM-1**

----

You will need to upgrade to `protein-sequence-annotation 1.0.7`. All you need to do is set `verbose=True`:

```python
PSALM.annotate(data,save_path="test_folder",verbose=True)
```

The prediction matrices will be in the form of `<save_path>/<sequence name>_<clan/fam>_preds.pkl`

In order to explore the prediction matrices (of shape Lx657 and Lx19632 for a sequence of length L for clan and family, respectively), you will need to use our mapping dictionary, which can either be downloaded from [this HuggingFace link](https://huggingface.co/ProteinSequenceAnnotation/PSALM-1-family/blob/main/maps.pkl) or with the following:

```python
from psalm import psalm_fam
PSALM_Family, maps = psalm_fam.from_pretrained("ProteinSequenceAnnotation/PSALM-1-family")
```

`maps` has two keys -- `idx_clan` and `idx_fam` -- which will help you go from index of the prediction matrix to the corresponding clan or family Pfam ID. "IDR" indicates no Pfam family annotation, and "NC0001" indices no Pfam clan membership.

I hope that helps! Please let me know if you have any other questions.
